/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttributionsRouteImport } from './routes/attributions'
import { Route as DescriptionRouteImport } from './routes/description'
import { Route as NewRouteImport } from './routes/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const DescriptionRoute = DescriptionRouteImport.update({
  id: '/description',
  path: '/description',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/description': typeof DescriptionRoute
  '/new': typeof NewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/description': typeof DescriptionRoute
  '/new': typeof NewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/description': typeof DescriptionRoute
  '/new': typeof NewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attributions' | '/description' | '/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attributions' | '/description' | '/new'
  id: '__root__' | '/' | '/attributions' | '/description' | '/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionsRoute: typeof AttributionsRoute
  DescriptionRoute: typeof DescriptionRoute
  NewRoute: typeof NewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributions': {
      id: '/attributions'
      path: '/attributions'
      fullPath: '/attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/description': {
      id: '/description'
      path: '/description'
      fullPath: '/description'
      preLoaderRoute: typeof DescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributionsRoute: AttributionsRoute,
  DescriptionRoute: DescriptionRoute,
  NewRoute: NewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
