/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttributionsRouteImport } from './routes/attributions'
import { Route as DescriptionRouteImport } from './routes/description'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as HumanPracticesRouteImport } from './routes/human-practices'
import { Route as NewRouteImport } from './routes/new'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const DescriptionRoute = DescriptionRouteImport.update({
  id: '/description',
  path: '/description',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanPracticesRoute = HumanPracticesRouteImport.update({
  id: '/human-practices',
  path: '/human-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/description': typeof DescriptionRoute
  '/engineering': typeof EngineeringRoute
  '/human-practices': typeof HumanPracticesRoute
  '/new': typeof NewRoute
  '/safety': typeof SafetyRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/description': typeof DescriptionRoute
  '/engineering': typeof EngineeringRoute
  '/human-practices': typeof HumanPracticesRoute
  '/new': typeof NewRoute
  '/safety': typeof SafetyRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/description': typeof DescriptionRoute
  '/engineering': typeof EngineeringRoute
  '/human-practices': typeof HumanPracticesRoute
  '/new': typeof NewRoute
  '/safety': typeof SafetyRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attributions'
    | '/description'
    | '/engineering'
    | '/human-practices'
    | '/new'
    | '/safety'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attributions'
    | '/description'
    | '/engineering'
    | '/human-practices'
    | '/new'
    | '/safety'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/attributions'
    | '/description'
    | '/engineering'
    | '/human-practices'
    | '/new'
    | '/safety'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionsRoute: typeof AttributionsRoute
  DescriptionRoute: typeof DescriptionRoute
  EngineeringRoute: typeof EngineeringRoute
  HumanPracticesRoute: typeof HumanPracticesRoute
  NewRoute: typeof NewRoute
  SafetyRoute: typeof SafetyRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributions': {
      id: '/attributions'
      path: '/attributions'
      fullPath: '/attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/description': {
      id: '/description'
      path: '/description'
      fullPath: '/description'
      preLoaderRoute: typeof DescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-practices': {
      id: '/human-practices'
      path: '/human-practices'
      fullPath: '/human-practices'
      preLoaderRoute: typeof HumanPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributionsRoute: AttributionsRoute,
  DescriptionRoute: DescriptionRoute,
  EngineeringRoute: EngineeringRoute,
  HumanPracticesRoute: HumanPracticesRoute,
  NewRoute: NewRoute,
  SafetyRoute: SafetyRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
