/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttributionsRouteImport } from './routes/attributions'
import { Route as ContributionRouteImport } from './routes/contribution'
import { Route as DescriptionRouteImport } from './routes/description'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as HumanPracticesRouteImport } from './routes/human-practices'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as SafetyAndSecurityRouteImport } from './routes/safety-and-security'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributionRoute = ContributionRouteImport.update({
  id: '/contribution',
  path: '/contribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DescriptionRoute = DescriptionRouteImport.update({
  id: '/description',
  path: '/description',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanPracticesRoute = HumanPracticesRouteImport.update({
  id: '/human-practices',
  path: '/human-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyAndSecurityRoute = SafetyAndSecurityRouteImport.update({
  id: '/safety-and-security',
  path: '/safety-and-security',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/contribution': typeof ContributionRoute
  '/description': typeof DescriptionRoute
  '/engineering': typeof EngineeringRoute
  '/human-practices': typeof HumanPracticesRoute
  '/playground': typeof PlaygroundRoute
  '/safety-and-security': typeof SafetyAndSecurityRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/contribution': typeof ContributionRoute
  '/description': typeof DescriptionRoute
  '/engineering': typeof EngineeringRoute
  '/human-practices': typeof HumanPracticesRoute
  '/playground': typeof PlaygroundRoute
  '/safety-and-security': typeof SafetyAndSecurityRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/contribution': typeof ContributionRoute
  '/description': typeof DescriptionRoute
  '/engineering': typeof EngineeringRoute
  '/human-practices': typeof HumanPracticesRoute
  '/playground': typeof PlaygroundRoute
  '/safety-and-security': typeof SafetyAndSecurityRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attributions'
    | '/contribution'
    | '/description'
    | '/engineering'
    | '/human-practices'
    | '/playground'
    | '/safety-and-security'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attributions'
    | '/contribution'
    | '/description'
    | '/engineering'
    | '/human-practices'
    | '/playground'
    | '/safety-and-security'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/attributions'
    | '/contribution'
    | '/description'
    | '/engineering'
    | '/human-practices'
    | '/playground'
    | '/safety-and-security'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionsRoute: typeof AttributionsRoute
  ContributionRoute: typeof ContributionRoute
  DescriptionRoute: typeof DescriptionRoute
  EngineeringRoute: typeof EngineeringRoute
  HumanPracticesRoute: typeof HumanPracticesRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SafetyAndSecurityRoute: typeof SafetyAndSecurityRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributions': {
      id: '/attributions'
      path: '/attributions'
      fullPath: '/attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribution': {
      id: '/contribution'
      path: '/contribution'
      fullPath: '/contribution'
      preLoaderRoute: typeof ContributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/description': {
      id: '/description'
      path: '/description'
      fullPath: '/description'
      preLoaderRoute: typeof DescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-practices': {
      id: '/human-practices'
      path: '/human-practices'
      fullPath: '/human-practices'
      preLoaderRoute: typeof HumanPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-and-security': {
      id: '/safety-and-security'
      path: '/safety-and-security'
      fullPath: '/safety-and-security'
      preLoaderRoute: typeof SafetyAndSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: 